PR to fix Issue #64
dlab-berkeley/R-Fundamentals-Legacy pull request #67
Opened 2022-01-08 20:41 UTC by asteves

This PR does the following: 

- Introduces the `here` package in Part2.R 
- Provides examples in Part2.R showing how the here package looks similar to the base `read.csv()` structure. 
- Updates all file paths to include calls to here
- Provides another example of installing packages and loading a packages. 
- Updates all solutions file paths to include call to here
- Updates README to add contributors and updated web links to contributors. 

Closes #64 

@pssachdeva

2022-01-09 00:14 UTC, pssachdeva commented
I will give this a review, but let's hold off on merging since it's rather short notice before the intensives next week.

2022-01-09 00:20 UTC, pssachdeva requested changes
This looks good, just asked for a couple small tweaks. Thanks for making the changes.

2022-01-09 00:20 UTC, pssachdeva commented on lessons/Part2.R
> +## One way to make this easier is to take advantage of the here R package. The here package enables easy file referencing by using the top level directory of our project to build the file paths. For
Can you make all reference to the `here` package in quotations whenever the occur in the comments? Since we're not in Markdown we don't get the benefit of code font, but I'd like to separate it so people know we're talking about the package.

2022-01-09 00:20 UTC, pssachdeva commented on lessons/Part2.R
> +
Can you add a short discussion on packages in R? I noticed we don't actually do it when we install dplyr; it'd be useful to have that here.

2022-01-09 00:41 UTC, asteves commented on lessons/Part2.R
> +## One way to make this easier is to take advantage of the here R package. The here package enables easy file referencing by using the top level directory of our project to build the file paths. For
Done

2022-01-09 00:42 UTC, asteves commented on lessons/Part2.R
> +
Done.

2022-01-09 00:42 UTC, asteves commented
Comments resolved. I'll let @pssachdeva decide when it is reasonable to merge.

2022-01-16 23:10 UTC, pssachdeva commented
We can go ahead and merge this, but this PR needs to be [rebased](https://docs.github.com/en/get-started/using-git/about-git-rebase) since other changes have occurred in the meantime. If you're not familiar with rebasing, feel free to reach out and we can chat through the process.

2022-01-16 23:14 UTC, asteves commented
What am I rebasing it off of?

2022-01-16 23:17 UTC, pssachdeva commented
Make sure you `main` branch is up to do. Then, rebase off `main`.

2022-01-16 23:57 UTC, asteves commented
@pssachdeva I think this is correct. Assuming it is, please go ahead and merge. @pssachdeva

2022-01-17 00:01 UTC, pssachdeva commented
I think it may have ended up doing a merge commit. At any rate, that's fine - everything looks good, so let's merge it.

2022-01-17 00:01 UTC, merged